using Criando_Minha_Primeira_API.Model.Interfaces;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Criando_Minha_Primeira_API.Model
{
    /// <summary>
    /// Represents a product entity within the application.
    /// Stores product information such as name, description,
    /// image, stock quantity, and its associated category.
    /// </summary>
    public class Product : IProduct
    {
        /// <summary>
        /// Gets the unique identifier of the product.
        /// This value is automatically generated by the database.
        /// </summary>
        [Key]
        public int Id { get; private set; }

        /// <summary>
        /// Gets or sets the product name.
        /// The name is required and cannot exceed 100 characters.
        /// </summary>
        [Required(ErrorMessage = "The product name is required.")]
        [StringLength(
            100,
            ErrorMessage = "The product name cannot exceed 100 characters.")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Represents the product price.
        /// Uses decimal type to ensure precision in monetary calculations.
        /// The Precision attribute configures the database column
        /// to support up to 12 digits with 4 decimal places.
        /// </summary>
        [Precision(12, 4)]
        [Range(0.01, 999_999_999)]
        public decimal Price { get; set; }

        /// <summary>
        /// Gets or sets the product description.
        /// The description must contain between 3 and 500 characters.
        /// This property is optional.
        /// </summary>
        [StringLength(
            500,
            MinimumLength = 3,
            ErrorMessage = "The description must contain between 3 and 500 characters.")]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the image URL representing the product.
        /// The image URL is required and cannot exceed 200 characters.
        /// </summary>
        [Required(ErrorMessage = "The product image URL is required.")]
        [StringLength(
            200,
            ErrorMessage = "The product image URL cannot exceed 200 characters.")]
        public string ImageUrl { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the available stock quantity of the product.
        /// The stock value must be between 0 and 10,000
        /// and supports up to 2 decimal places.
        /// </summary>
        [Range(
            0,
            10_000,
            ErrorMessage = "The stock value must be between 0 and 10,000.")]
        [Precision(10, 2)]
        public decimal Stock { get; set; }

        /// <summary>
        /// Represents the date and time when the product was created.
        /// The value is automatically initialized using UTC time
        /// to ensure consistency across different time zones.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Gets or sets the identifier of the category
        /// associated with the product.
        /// This property is optional.
        /// </summary>
        [Range(
            1,
            int.MaxValue,
            ErrorMessage = "Invalid category identifier.")]
        public int? CategoryId { get; set; } = 0;

        /// <summary>
        /// Gets or sets the category associated with the product.
        /// Represents the navigation property used by Entity Framework Core.
        /// </summary>
        [ForeignKey(nameof(CategoryId))]
        [JsonIgnore]
        public Category? Category { get; set; }
    }
}
